# PostgreSQL Gaming Database Alert Rules

groups:
  - name: postgresql_gaming_database
    rules:
      # Connection Pool Alerts
      - alert: PostgreSQLConnectionPoolHigh
        expr: postgresql_connections_total / postgresql_max_connections * 100 > 80
        for: 2m
        labels:
          severity: warning
          service: postgresql
          component: connection_pool
        annotations:
          summary: "PostgreSQL connection pool usage is high"
          description: "Connection pool usage is {{ $value }}% on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/connection-pool-high"

      - alert: PostgreSQLConnectionPoolCritical
        expr: postgresql_connections_total / postgresql_max_connections * 100 > 90
        for: 1m
        labels:
          severity: critical
          service: postgresql
          component: connection_pool
        annotations:
          summary: "PostgreSQL connection pool usage is critical"
          description: "Connection pool usage is {{ $value }}% on database {{ $labels.database }}. Immediate action required."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/connection-pool-critical"

      # Cache Hit Ratio Alerts
      - alert: PostgreSQLCacheHitRatioLow
        expr: postgresql_cache_hit_ratio < 95
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: cache
        annotations:
          summary: "PostgreSQL cache hit ratio is low"
          description: "Cache hit ratio is {{ $value }}% on database {{ $labels.database }}. Consider increasing shared_buffers."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/cache-hit-ratio-low"

      - alert: PostgreSQLCacheHitRatioCritical
        expr: postgresql_cache_hit_ratio < 90
        for: 3m
        labels:
          severity: critical
          service: postgresql
          component: cache
        annotations:
          summary: "PostgreSQL cache hit ratio is critically low"
          description: "Cache hit ratio is {{ $value }}% on database {{ $labels.database }}. Performance severely impacted."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/cache-hit-ratio-critical"

      # Query Performance Alerts
      - alert: PostgreSQLSlowQueries
        expr: postgresql_query_mean_time_ms{operation=~"Game.*|Player.*|Move.*"} > 100
        for: 3m
        labels:
          severity: warning
          service: postgresql
          component: query_performance
        annotations:
          summary: "PostgreSQL gaming queries are slow"
          description: "{{ $labels.operation }} queries averaging {{ $value }}ms on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/slow-queries"

      - alert: PostgreSQLVerySlowQueries
        expr: postgresql_query_mean_time_ms{operation=~"Game.*|Player.*|Move.*"} > 500
        for: 1m
        labels:
          severity: critical
          service: postgresql
          component: query_performance
        annotations:
          summary: "PostgreSQL gaming queries are very slow"
          description: "{{ $labels.operation }} queries averaging {{ $value }}ms on database {{ $labels.database }}. Gaming experience severely impacted."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/very-slow-queries"

      # Lock and Contention Alerts
      - alert: PostgreSQLLockWaits
        expr: postgresql_lock_waits_total > 5
        for: 2m
        labels:
          severity: warning
          service: postgresql
          component: locks
        annotations:
          summary: "PostgreSQL has lock waits"
          description: "{{ $value }} lock waits detected on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/lock-waits"

      - alert: PostgreSQLLockWaitsCritical
        expr: postgresql_lock_waits_total > 15
        for: 1m
        labels:
          severity: critical
          service: postgresql
          component: locks
        annotations:
          summary: "PostgreSQL has critical lock waits"
          description: "{{ $value }} lock waits detected on database {{ $labels.database }}. Possible deadlock situation."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/lock-waits-critical"

      # Long Running Transaction Alerts
      - alert: PostgreSQLLongRunningTransactions
        expr: postgresql_long_running_transactions_total > 3
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: transactions
        annotations:
          summary: "PostgreSQL has long-running transactions"
          description: "{{ $value }} long-running transactions (>5 minutes) on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/long-transactions"

      - alert: PostgreSQLVeryLongRunningTransactions
        expr: postgresql_long_running_transactions_total > 1
        for: 15m
        labels:
          severity: critical
          service: postgresql
          component: transactions
        annotations:
          summary: "PostgreSQL has very long-running transactions"
          description: "{{ $value }} very long-running transactions (>15 minutes) on database {{ $labels.database }}. Possible blocking situation."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/very-long-transactions"

      # Disk Usage Alerts
      - alert: PostgreSQLDiskUsageHigh
        expr: (postgresql_database_size_bytes / postgresql_disk_total_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: storage
        annotations:
          summary: "PostgreSQL disk usage is high"
          description: "Disk usage is {{ $value }}% on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/disk-usage-high"

      - alert: PostgreSQLDiskUsageCritical
        expr: (postgresql_database_size_bytes / postgresql_disk_total_bytes) * 100 > 90
        for: 2m
        labels:
          severity: critical
          service: postgresql
          component: storage
        annotations:
          summary: "PostgreSQL disk usage is critical"
          description: "Disk usage is {{ $value }}% on database {{ $labels.database }}. Risk of service interruption."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/disk-usage-critical"

      # Gaming-Specific Alerts
      - alert: PostgreSQLGamingHighErrorRate
        expr: rate(postgresql_gaming_errors_total[5m]) * 60 > 10
        for: 3m
        labels:
          severity: warning
          service: postgresql
          component: gaming
        annotations:
          summary: "High gaming error rate in PostgreSQL"
          description: "Gaming errors rate is {{ $value }} errors/minute on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/gaming-high-error-rate"

      - alert: PostgreSQLGamingNoActiveGames
        expr: postgresql_gaming_active_games < 1
        for: 10m
        labels:
          severity: warning
          service: postgresql
          component: gaming
        annotations:
          summary: "No active games in PostgreSQL"
          description: "No active games detected for 10 minutes on database {{ $labels.database }}. Possible service issue."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/no-active-games"

      - alert: PostgreSQLGamingHighMoveLatency
        expr: postgresql_gaming_move_latency_p95 > 1000
        for: 5m
        labels:
          severity: critical
          service: postgresql
          component: gaming
        annotations:
          summary: "High gaming move latency in PostgreSQL"
          description: "95th percentile move latency is {{ $value }}ms on database {{ $labels.database }}. Gaming experience severely impacted."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/high-move-latency"

      # Replication Alerts (if using read replicas)
      - alert: PostgreSQLReplicationLag
        expr: postgresql_replication_lag_bytes / 1024 / 1024 > 100
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: replication
        annotations:
          summary: "PostgreSQL replication lag is high"
          description: "Replication lag is {{ $value }}MB on replica {{ $labels.replica }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/replication-lag"

      - alert: PostgreSQLReplicationLagCritical
        expr: postgresql_replication_lag_bytes / 1024 / 1024 > 500
        for: 2m
        labels:
          severity: critical
          service: postgresql
          component: replication
        annotations:
          summary: "PostgreSQL replication lag is critical"
          description: "Replication lag is {{ $value }}MB on replica {{ $labels.replica }}. Risk of data loss."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/replication-lag-critical"

      # Table Bloat Alerts
      - alert: PostgreSQLTableBloat
        expr: postgresql_table_dead_tuple_ratio{table=~"game_.*|player.*|websocket.*"} > 20
        for: 10m
        labels:
          severity: warning
          service: postgresql
          component: maintenance
        annotations:
          summary: "PostgreSQL table has high bloat"
          description: "Table {{ $labels.table }} has {{ $value }}% dead tuples on database {{ $labels.database }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/table-bloat"

      - alert: PostgreSQLTableBloatCritical
        expr: postgresql_table_dead_tuple_ratio{table=~"game_.*|player.*|websocket.*"} > 40
        for: 5m
        labels:
          severity: critical
          service: postgresql
          component: maintenance
        annotations:
          summary: "PostgreSQL table has critical bloat"
          description: "Table {{ $labels.table }} has {{ $value }}% dead tuples on database {{ $labels.database }}. Immediate vacuum required."
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/table-bloat-critical"

      # Database Availability Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
          component: availability
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is down"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/database-down"

      - alert: PostgreSQLTooManyConnections
        expr: postgresql_connections_total > postgresql_max_connections * 0.95
        for: 2m
        labels:
          severity: critical
          service: postgresql
          component: connection_pool
        annotations:
          summary: "PostgreSQL is running out of connections"
          description: "PostgreSQL has {{ $value }} connections, approaching limit of {{ $labels.max_connections }}"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/too-many-connections"

      # Capacity Planning Alerts
      - alert: PostgreSQLDiskGrowthRateHigh
        expr: predict_linear(postgresql_database_size_bytes[1h], 24*3600) - postgresql_database_size_bytes > postgresql_disk_total_bytes * 0.1
        for: 30m
        labels:
          severity: warning
          service: postgresql
          component: capacity_planning
        annotations:
          summary: "PostgreSQL database growing rapidly"
          description: "Database {{ $labels.database }} is predicted to grow by {{ $value | humanize1024 }}B in the next 24 hours"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/rapid-growth"

      - alert: PostgreSQLConnectionGrowthRateHigh
        expr: predict_linear(postgresql_connections_total[30m], 3600) > postgresql_max_connections * 0.8
        for: 15m
        labels:
          severity: warning
          service: postgresql
          component: capacity_planning
        annotations:
          summary: "PostgreSQL connection usage growing rapidly"
          description: "Connection usage on {{ $labels.database }} is predicted to reach 80% of capacity within 1 hour"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/connection-growth"

  # Gaming Business Logic Alerts
  - name: postgresql_gaming_business
    rules:
      - alert: PostgreSQLGamingAverageGameDurationAbnormal
        expr: postgresql_gaming_avg_game_duration_minutes < 5 or postgresql_gaming_avg_game_duration_minutes > 120
        for: 15m
        labels:
          severity: warning
          service: postgresql
          component: gaming_business
        annotations:
          summary: "Abnormal average game duration"
          description: "Average game duration is {{ $value }} minutes, which is outside normal range (5-120 minutes)"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/abnormal-game-duration"

      - alert: PostgreSQLGamingPlayerConnectionIssues
        expr: rate(postgresql_gaming_disconnections_total[5m]) / rate(postgresql_gaming_connections_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: gaming_business
        annotations:
          summary: "High player disconnection rate"
          description: "Player disconnection rate is {{ $value | humanizePercentage }} of connections"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/high-disconnection-rate"

      - alert: PostgreSQLGamingLowGameCreationRate
        expr: rate(postgresql_gaming_game_creation_total[10m]) * 60 < 1
        for: 15m
        labels:
          severity: warning
          service: postgresql
          component: gaming_business
        annotations:
          summary: "Low game creation rate"
          description: "Game creation rate is {{ $value }} games/minute, below expected threshold"
          runbook_url: "https://github.com/hokm-game/runbooks/postgresql/low-game-creation"
