# AlertManager configuration for PostgreSQL HA

global:
  smtp_smarthost: 'smtp.company.com:587'
  smtp_from: 'alerts@company.com'
  smtp_auth_username: 'alerts@company.com'
  smtp_auth_password: 'smtp_password'
  smtp_require_tls: true

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook.default'
  routes:
    # Critical database alerts - immediate notification
    - match:
        severity: critical
      receiver: 'database-critical'
      group_wait: 5s
      repeat_interval: 5m
      
    # PostgreSQL specific alerts
    - match:
        service: postgresql
      receiver: 'database-team'
      
    # Gaming performance alerts
    - match:
        component: gaming
      receiver: 'gaming-team'
      
    # Infrastructure alerts
    - match_re:
        service: (haproxy|patroni|etcd)
      receiver: 'infrastructure-team'

# Inhibition rules to prevent spam
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
    
  # Inhibit replica alerts if primary is down
  - source_match:
      alertname: 'PostgreSQLPrimaryDown'
    target_match_re:
      alertname: 'PostgreSQL.*Replica.*'
    equal: ['cluster']

# Notification receivers
receivers:
  - name: 'web.hook.default'
    webhook_configs:
      - url: 'http://webhook-receiver:8080/alerts'
        send_resolved: true

  - name: 'database-critical'
    email_configs:
      - to: 'dba-oncall@company.com'
        subject: 'CRITICAL: PostgreSQL Alert - {{ .GroupLabels.alertname }}'
        html: |
          <h2>Critical Database Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Instance:</strong> {{ .CommonLabels.instance }}</p>
          <p><strong>Description:</strong> {{ range .Alerts }}{{ .Annotations.description }}{{ end }}</p>
          <p><strong>Time:</strong> {{ .Alerts.StartsAt }}</p>
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#database-alerts'
        title: 'CRITICAL: PostgreSQL Alert'
        text: |
          Alert: {{ .GroupLabels.alertname }}
          Instance: {{ .CommonLabels.instance }}
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        send_resolved: true
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: 'CRITICAL: {{ .GroupLabels.alertname }} on {{ .CommonLabels.instance }}'

  - name: 'database-team'
    email_configs:
      - to: 'database-team@company.com'
        subject: 'PostgreSQL Alert - {{ .GroupLabels.alertname }}'
        html: |
          <h2>PostgreSQL Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Instance:</strong> {{ .CommonLabels.instance }}</p>
          <p><strong>Description:</strong> {{ range .Alerts }}{{ .Annotations.description }}{{ end }}</p>
          <p><strong>Time:</strong> {{ .Alerts.StartsAt }}</p>
          {{ if .Alerts.ResolvedAt }}<p><strong>Resolved:</strong> {{ .Alerts.ResolvedAt }}</p>{{ end }}
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#database-team'
        title: 'PostgreSQL Alert: {{ .GroupLabels.alertname }}'
        text: |
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        send_resolved: true

  - name: 'gaming-team'
    email_configs:
      - to: 'gaming-team@company.com'
        subject: 'Gaming Performance Alert - {{ .GroupLabels.alertname }}'
        html: |
          <h2>Gaming Performance Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Instance:</strong> {{ .CommonLabels.instance }}</p>
          <p><strong>Description:</strong> {{ range .Alerts }}{{ .Annotations.description }}{{ end }}</p>
          <p><strong>Time:</strong> {{ .Alerts.StartsAt }}</p>
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#gaming-performance'
        title: 'Gaming Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        send_resolved: true

  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@company.com'
        subject: 'Infrastructure Alert - {{ .GroupLabels.alertname }}'
        html: |
          <h2>Infrastructure Alert</h2>
          <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Instance:</strong> {{ .CommonLabels.instance }}</p>
          <p><strong>Description:</strong> {{ range .Alerts }}{{ .Annotations.description }}{{ end }}</p>
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#infrastructure'
        title: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
        text: |
          Service: {{ .CommonLabels.service }}
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        send_resolved: true
