# Prometheus configuration for PostgreSQL HA monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hokm-postgresql-ha'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics via postgres-exporter
  - job_name: 'postgresql-primary'
    static_configs:
      - targets: ['postgres-exporter-primary:9187']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgresql-primary

  - job_name: 'postgresql-replica1'
    static_configs:
      - targets: ['postgres-exporter-replica1:9187']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgresql-replica1

  - job_name: 'postgresql-replica2'
    static_configs:
      - targets: ['postgres-exporter-replica2:9187']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgresql-replica2

  # Patroni REST API monitoring
  - job_name: 'patroni-primary'
    static_configs:
      - targets: ['postgresql-primary:8008']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: patroni-primary

  - job_name: 'patroni-replica1'
    static_configs:
      - targets: ['postgresql-replica1:8009']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: patroni-replica1

  - job_name: 'patroni-replica2'
    static_configs:
      - targets: ['postgresql-replica2:8010']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: patroni-replica2

  # HAProxy monitoring
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8081']
    scrape_interval: 15s
    metrics_path: /stats/prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: haproxy

  # PgBouncer monitoring (if metrics endpoint available)
  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer:9127']
    scrape_interval: 15s
    scrape_timeout: 5s

  # etcd cluster monitoring
  - job_name: 'etcd'
    static_configs:
      - targets: 
        - 'etcd1:2379'
        - 'etcd2:2379'
        - 'etcd3:2379'
    scrape_interval: 15s
    metrics_path: /metrics

  # System metrics (if node-exporter is deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter-primary:9100'
        - 'node-exporter-replica1:9100'
        - 'node-exporter-replica2:9100'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        regex: 'node-exporter-(.+):9100'
        target_label: instance
        replacement: '${1}'

# Gaming-specific custom metrics collection
  - job_name: 'hokm-game-metrics'
    static_configs:
      - targets: ['hokm-backend:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
