version: '3.8'

services:
  # Primary PostgreSQL Server
  postgres-primary:
    image: postgres:13
    container_name: hokm_postgres_primary
    environment:
      POSTGRES_DB: hokm_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: repl_password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init_primary.sql:/docker-entrypoint-initdb.d/01_init_primary.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - fault_tolerant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Standby PostgreSQL Server
  postgres-standby:
    image: postgres:13
    container_name: hokm_postgres_standby
    environment:
      POSTGRES_DB: hokm_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGUSER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_standby_data:/var/lib/postgresql/data
      - ./standby/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./standby/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./setup_standby.sh:/docker-entrypoint-initdb.d/setup_standby.sh
    depends_on:
      - postgres-primary
    networks:
      - fault_tolerant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Master (Primary)
  redis-master:
    image: redis:7-alpine
    container_name: hokm_redis_master
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
      - ./redis/master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - fault_tolerant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis Replica (Backup)
  redis-replica:
    image: redis:7-alpine
    container_name: hokm_redis_replica
    ports:
      - "6380:6379"
    volumes:
      - redis_replica_data:/data
      - ./redis/replica.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      - fault_tolerant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: hokm_redis_sentinel_1
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - fault_tolerant_network

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: hokm_redis_sentinel_2
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - fault_tolerant_network

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: hokm_redis_sentinel_3
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - fault_tolerant_network

  # Load Balancer / Proxy
  nginx:
    image: nginx:alpine
    container_name: hokm_loadbalancer
    ports:
      - "8080:80"
      - "8765:8765"
      - "8766:8766"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres-primary
      - postgres-standby
      - redis-master
      - redis-replica
    networks:
      - fault_tolerant_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_primary_data:
  postgres_standby_data:
  redis_master_data:
  redis_replica_data:

networks:
  fault_tolerant_network:
    driver: bridge
    name: hokm_fault_tolerant
